# Site settings
title: Nicholas Chedid
email: nicholasfc@gmail.com
author: Nicholas Chedid
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nicholaschedid.com" # the base hostname & protocol for your site
permalink: /blog/:title

google_analytics:
linkedin_username: nicholaschedid
github_username:  nicholasfc

# Build settings
markdown: kramdown
highlighter: pygments
paginate: 3
sass:
  sass_dir: _sass
  style: :compressed
